parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    oliverde8\ComfySyliusAdminBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    # Sylius menu
    oliverde8\ComfySyliusAdminBundle\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    # Scope resolver
    oliverde8\ComfyBundle\Resolver\ScopeResolverInterface:
        class: oliverde8\ComfySyliusAdminBundle\Resolver\ChannelScopeResolver
        arguments:
            "$channelRepository": '@sylius.repository.channel'
            "$channelContext": '@sylius.context.channel'
            "$localeContext": '@sylius.context.locale'
            "$defaultScope": 'base'
            "$defaultScopeName": 'Base'
